#!/bin/bash
if [[ "$build_mode" == "single" ]]; then
echo "SINGLE"
cd /plugins
go mod download
go build -buildmode=plugin -o /plugins/plugin.so /plugins/plugin.go
fi


if [[ "$build_mode" == "group" ]]; then
echo "GROUP"
cd /plugins
ls
for directory in `find /plugins -mindepth 1 -maxdepth 1  -type d `
do
cd $directory
echo $directory found
go mod download
go build -buildmode=plugin -o $directory.so plugin.go
cd ..
done
fi